name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        pwd
        ls -la
